-- ============================================
-- Supabase Migration: GLA Negocio Local MVP
-- Run this in Supabase SQL Editor
-- ============================================

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]',
  total REAL NOT NULL DEFAULT 0,
  payment_method TEXT DEFAULT '',
  status TEXT CHECK (status IN ('pending','preparing','delivered','cancelled','expirado')) NOT NULL DEFAULT 'pending',
  notes TEXT DEFAULT '',
  mp_payment_id TEXT DEFAULT '',
  payment_status TEXT DEFAULT 'pending',
  mp_payment_data JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Pending orders (pre-payment)
CREATE TABLE IF NOT EXISTS pending_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_ref TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]',
  total REAL NOT NULL DEFAULT 0,
  payment_method TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  payment_type TEXT DEFAULT 'card',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Catalog / Products
CREATE TABLE IF NOT EXISTS catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  price REAL NOT NULL DEFAULT 0,
  category TEXT DEFAULT '',
  image_path TEXT DEFAULT '',
  active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Payment methods
CREATE TABLE IF NOT EXISTS payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0,
  details JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Promotions
CREATE TABLE IF NOT EXISTS promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  price REAL NOT NULL DEFAULT 0,
  image_path TEXT DEFAULT '',
  type TEXT CHECK (type IN ('promotion','package')) NOT NULL DEFAULT 'promotion',
  active INTEGER NOT NULL DEFAULT 1,
  details JSONB DEFAULT '[]',
  config JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Owner config
CREATE TABLE IF NOT EXISTS owner_config (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  whatsapp_phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  smtp_host TEXT DEFAULT 'smtp.gmail.com',
  smtp_port INTEGER DEFAULT 587,
  smtp_user TEXT DEFAULT '',
  smtp_pass TEXT DEFAULT '',
  notify_orders INTEGER NOT NULL DEFAULT 1,
  notify_payments INTEGER NOT NULL DEFAULT 1
);

INSERT INTO owner_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Users / Admin
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin','operator')) NOT NULL DEFAULT 'operator'
);

-- Seed default data
INSERT INTO payment_methods (name, enabled, details) VALUES
  ('Efectivo', 1, '["Pago en caja al retirar tu pedido"]'),
  ('Tarjeta', 1, '["Pago con tarjeta de credito o debito via MercadoPago"]'),
  ('Transferencia', 1, '["CLABE: 123456789012345678","Banco: BBVA","Titular: Cafeteria Luna Test"]')
ON CONFLICT (name) DO NOTHING;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_mp_payment_id ON orders(mp_payment_id);
CREATE INDEX IF NOT EXISTS idx_pending_orders_ref ON pending_orders(external_ref);
CREATE INDEX IF NOT EXISTS idx_catalog_active ON catalog(active);
CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(active);

-- Enable realtime for orders (optional)
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
