[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_SUPABASE_URL = "https://jjplupzhtpkjfqzlfsoh.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_XFKTzdua4PQXlUwpQnn6aQ_BtASbEJw"
  NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY = "APP_USR-d0c7119a-128d-4914-ba5c-09ab930c3e6d"
  NEXT_PUBLIC_MP_MODE = "production"
  NEXT_PUBLIC_SIMULATE_PAYMENTS = "false"
  NEXT_PUBLIC_STATEMENT_DESCRIPTOR = "CAFETERIALUNATEST"

[[plugins]]
  package = "@netlify/plugin-nextjs"
